/* Automatically generated by './build/bin/build-entry.js' */

import Aside from './components/aside/index.js';
import Col from './components/col/index.js';
import Container from './components/container/index.js';
import Footer from './components/footer/index.js';
import Header from './components/header/index.js';
import Main from './components/main/index.js';
import Row from './components/row/index.js';
import Button from './components/button/index.js';
import ButtonGroup from './components/button-group/index.js';
import Link from './components/link/index.js';
import Radio from './components/radio/index.js';
import RadioGroup from './components/radio-group/index.js';
// import CollapseTransition from 'element-ui/src/transitions/collapse-transition';

const components = [
  Aside,
  Col,
  Container,
  Footer,
  Header,
  Main,
  Row,
  Button,
  ButtonGroup,
  Link,
  Radio,
  RadioGroup,


];

const install = function(Vue, opts = {}) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });


  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

  // Vue.prototype.$loading = Loading.service;
  // Vue.prototype.$msgbox = MessageBox;
  // Vue.prototype.$alert = MessageBox.alert;
  // Vue.prototype.$confirm = MessageBox.confirm;
  // Vue.prototype.$prompt = MessageBox.prompt;
  // Vue.prototype.$notify = Notification;
  // Vue.prototype.$message = Message;

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.1.0',
  install,
  Aside,
  Col,
  Container,
  Footer,
  Header,
  Main,
  Row,
  Button,
  ButtonGroup,
  Link,
  Radio,
  RadioGroup
  
};
